"""Real PostgreSQL / HTTP contract tests. Refuses non-loopback services and databases.

Run with PHOTOCRAFT_FIXTURE pointing at the fixture generated by the Rust example.
No test authentication route or production bypass is added to the application.
"""
import concurrent.futures
import hashlib
import io
import os
from pathlib import Path
import secrets
import unittest
from urllib.parse import urlparse
import uuid
import zipfile

import psycopg
import requests

BASE = os.environ.get("PHOTOCRAFT_TEST_ORIGIN", "http://127.0.0.1:8876")
DATABASE = os.environ.get("PHOTOCRAFT_TEST_DATABASE_URL", "postgresql://photocraft_test@127.0.0.1:55438/postgres")
CHUNK = 524288


class CloudContract(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        for value in [BASE, DATABASE]:
            if urlparse(value).hostname not in {"localhost", "127.0.0.1", "::1"}:
                raise RuntimeError("These tests seed synthetic accounts and require isolated loopback services")
        cls.fixture = Path(os.environ["PHOTOCRAFT_FIXTURE"]).read_bytes()
        cls.db = psycopg.connect(DATABASE, autocommit=True)
        cls.accounts = []
        for name in ["Owner", "Editor", "Viewer", "Outsider"]:
            ident, token = str(uuid.uuid4()), secrets.token_hex(32)
            email = f"{ident}@example.invalid"
            cls.db.execute("INSERT INTO photocraft.accounts(id,email,name) VALUES(%s,%s,%s)", (ident, email, name))
            cls.db.execute("INSERT INTO photocraft.sessions(hash,account_id) VALUES(%s,%s)", (hashlib.sha256(token.encode()).hexdigest(), ident))
            session = requests.Session()
            session.trust_env = False
            session.headers["Origin"] = BASE
            session.cookies.set("pc_session", token)
            cls.accounts.append((ident, email, session))
        cls.owner, cls.editor, cls.viewer, cls.outsider = [v[2] for v in cls.accounts]
        cls.anon = requests.Session()
        cls.anon.trust_env = False
        cls.anon.headers["Origin"] = BASE

    @classmethod
    def tearDownClass(cls):
        # This database belongs to this test run, but remove only these synthetic accounts.
        ids = [a[0] for a in cls.accounts]
        cls.db.execute("DELETE FROM photocraft.projects WHERE owner_id=ANY(%s::uuid[])", (ids,))
        cls.db.execute("DELETE FROM photocraft.sessions WHERE account_id=ANY(%s::uuid[])", (ids,))
        cls.db.execute("DELETE FROM photocraft.accounts WHERE id=ANY(%s::uuid[])", (ids,))
        cls.db.close()

    def req(self, session, method, path, status=200, **kwargs):
        res = session.request(method, BASE + path, timeout=20, **kwargs)
        self.assertEqual(res.status_code, status, f"{method} {path}: {res.status_code} {res.text[:250]}")
        return res

    def tearDown(self):
        self.db.execute("DELETE FROM photocraft.uploads WHERE author_id=ANY(%s::uuid[])", ([a[0] for a in self.accounts],))

    def project(self):
        return self.req(self.owner, "POST", "/api/projects", json={"title": "Synthetic test"}).json()["id"]

    def member(self, pid, who, role):
        return self.req(self.owner, "PUT", f"/api/projects/{pid}/members", json={"email": self.accounts[who][1], "role": role})

    def begin(self, pid, data=None, base=0, session=None, **extra):
        data = self.fixture if data is None else data
        payload = {"base_revision": base, "bytes": len(data), "parts": (len(data)+CHUNK-1)//CHUNK,
                   "sha256": hashlib.sha256(data).hexdigest(), "title": "Test save", "width": 64, "height": 48, **extra}
        return self.req(session or self.owner, "POST", f"/api/projects/{pid}/uploads", json=payload).json()["id"]

    def upload(self, pid, data=None, base=0, session=None, commit_status=200):
        data = self.fixture if data is None else data
        session = session or self.owner
        uid = self.begin(pid, data, base, session)
        for i in range(0, len(data), CHUNK):
            self.req(session, "PUT", f"/api/uploads/{uid}/{i//CHUNK}", data=data[i:i+CHUNK])
        return self.req(session, "POST", f"/api/uploads/{uid}/commit", status=commit_status, json={})

    def test_01_health_and_config(self):
        self.assertEqual(self.req(self.anon, "GET", "/healthz").json()["status"], "ok")
        cfg = self.req(self.anon, "GET", "/api/config").json()
        self.assertTrue(cfg["cloud"])
        self.assertEqual(cfg["chunkBytes"], CHUNK)
        self.assertNotIn("DATABASE_URL", cfg)

    def test_02_authentication_is_required(self):
        for method, path in [("GET", "/api/me"), ("GET", "/api/projects"), ("POST", "/api/projects")]:
            with self.subTest(path=path, method=method):
                self.req(self.anon, method, path, status=401, json={"title": "Denied"})

    def test_03_csrf_missing_and_foreign_origin(self):
        for origin in ["https://evil.invalid", "null", ""]:
            with self.subTest(origin=origin):
                self.req(self.owner, "POST", "/api/projects", status=403, headers={"Origin": origin}, json={"title": "Denied"})

    def test_04_account_identity(self):
        me = self.req(self.owner, "GET", "/api/me").json()
        self.assertEqual(me["id"], self.accounts[0][0])
        self.assertEqual(me["email"], self.accounts[0][1])

    def test_05_title_validation(self):
        for title in ["", "  ", "a"*161, "a\u0000b"]:
            with self.subTest(title=repr(title)[:30]):
                self.req(self.owner, "POST", "/api/projects", status=400, json={"title": title})
        self.req(self.owner, "POST", "/api/projects", json={"title": "日本語 · Café <script>alert(1)</script>"})

    def test_06_cross_account_isolation(self):
        pid = self.project()
        for path in ["", "/versions", "/content", "/comments", "/members", "/thumbnail"]:
            with self.subTest(path=path):
                self.req(self.outsider, "GET", f"/api/projects/{pid}{path}", status=404)
        ids = [p["id"] for p in self.req(self.outsider, "GET", "/api/projects").json()]
        self.assertNotIn(pid, ids)
        self.req(self.outsider, "PATCH", f"/api/projects/{pid}", status=404, json={"title": "Stolen"})

    def test_07_roles_and_revocation(self):
        pid = self.project()
        self.member(pid, 1, "edit")
        self.member(pid, 2, "view")
        for who in [self.editor, self.viewer]:
            self.req(who, "GET", f"/api/projects/{pid}")
            self.req(who, "PATCH", f"/api/projects/{pid}", status=404, json={"title": "Denied"})
            self.req(who, "POST", f"/api/projects/{pid}/share", status=404)
        self.upload(pid, session=self.editor)
        self.req(self.viewer, "POST", f"/api/projects/{pid}/uploads", status=404,
                 json={"base_revision": 1, "bytes": 1, "parts": 1, "sha256": "a"*64, "title": "Denied", "width": 64, "height": 48})
        self.member(pid, 1, "remove")
        self.req(self.editor, "GET", f"/api/projects/{pid}", status=404)

    def test_08_native_roundtrip_and_history(self):
        pid = self.project()
        self.upload(pid)
        self.upload(pid, base=1)
        history = self.req(self.owner, "GET", f"/api/projects/{pid}/versions").json()
        self.assertEqual([v["revision"] for v in history], [2, 1])
        for rev in [1, 2]:
            data = self.req(self.owner, "GET", f"/api/projects/{pid}/content?revision={rev}&part=0").content
            self.assertEqual(data, self.fixture)

    def test_09_multimegabyte_binary_roundtrip(self):
        pid = self.project()
        f = io.BytesIO(self.fixture)
        with zipfile.ZipFile(f, "a", compression=zipfile.ZIP_STORED) as archive:
            archive.writestr("synthetic-padding.bin", secrets.token_bytes(5*1024*1024))
        data = f.getvalue()
        self.upload(pid, data)
        out = b"".join(self.req(self.owner, "GET", f"/api/projects/{pid}/content?part={i}").content for i in range((len(data)+CHUNK-1)//CHUNK))
        self.assertEqual(hashlib.sha256(out).digest(), hashlib.sha256(data).digest())

    def test_10_partial_upload_preserves_saved_version(self):
        pid = self.project()
        self.upload(pid)
        uid = self.begin(pid, base=1)
        self.req(self.owner, "POST", f"/api/uploads/{uid}/commit", status=400, json={})
        self.assertEqual(self.req(self.owner, "GET", f"/api/projects/{pid}").json()["revision"], 1)

    def test_11_corruption_is_rejected(self):
        pid = self.project()
        uid = self.begin(pid, sha256="0"*64)
        self.req(self.owner, "PUT", f"/api/uploads/{uid}/0", data=self.fixture)
        self.req(self.owner, "POST", f"/api/uploads/{uid}/commit", status=400, json={})
        self.assertEqual(self.req(self.owner, "GET", f"/api/projects/{pid}").json()["revision"], 0)

    def test_12_chunk_bounds_and_foreign_upload(self):
        pid = self.project()
        uid = self.begin(pid)
        for part in [-1, 1, 200]:
            with self.subTest(part=part):
                self.req(self.owner, "PUT", f"/api/uploads/{uid}/{part}", status=400, data=self.fixture)
        self.req(self.owner, "PUT", f"/api/uploads/{uid}/0", status=400, data=b"short")
        self.req(self.outsider, "PUT", f"/api/uploads/{uid}/0", status=404, data=self.fixture)
        self.req(self.outsider, "POST", f"/api/uploads/{uid}/commit", status=404, json={})

    def test_13_stale_writer_conflict(self):
        pid = self.project()
        self.upload(pid)
        self.upload(pid, commit_status=409)
        self.assertEqual(self.req(self.owner, "GET", f"/api/projects/{pid}").json()["revision"], 1)

    def test_14_simultaneous_commit_is_atomic(self):
        pid = self.project()
        ids = [self.begin(pid), self.begin(pid)]
        for uid in ids:
            self.req(self.owner, "PUT", f"/api/uploads/{uid}/0", data=self.fixture)
        def commit(uid):
            return self.owner.post(BASE+f"/api/uploads/{uid}/commit", json={}, timeout=20).status_code
        with concurrent.futures.ThreadPoolExecutor(2) as pool:
            codes = list(pool.map(commit, ids))
        self.assertEqual(sorted(codes), [200, 409])
        self.assertEqual(len(self.req(self.owner, "GET", f"/api/projects/{pid}/versions").json()), 1)

    def test_15_public_links_revoke_and_rotate(self):
        pid = self.project()
        self.upload(pid)
        first = self.req(self.owner, "POST", f"/api/projects/{pid}/share").json()["url"].split("share=")[1]
        self.req(self.anon, "GET", f"/api/share/{first}")
        self.assertEqual(self.req(self.anon, "GET", f"/api/share/{first}/content?part=0").content, self.fixture)
        second = self.req(self.owner, "POST", f"/api/projects/{pid}/share").json()["url"].split("share=")[1]
        self.req(self.anon, "GET", f"/api/share/{first}", status=404)
        self.req(self.owner, "DELETE", f"/api/projects/{pid}/share")
        self.req(self.anon, "GET", f"/api/share/{second}", status=404)

    def test_16_trash_and_restore(self):
        pid = self.project()
        self.upload(pid)
        key = self.req(self.owner, "POST", f"/api/projects/{pid}/share").json()["url"].split("share=")[1]
        self.req(self.owner, "PATCH", f"/api/projects/{pid}", json={"trashed": True})
        self.req(self.anon, "GET", f"/api/share/{key}", status=404)
        self.upload(pid, base=1, commit_status=400)
        self.req(self.owner, "PATCH", f"/api/projects/{pid}", json={"trashed": False})
        self.req(self.anon, "GET", f"/api/share/{key}")

    def test_17_duplicate_and_folder(self):
        pid = self.project()
        self.upload(pid)
        self.member(pid, 2, "view")
        copy = self.req(self.viewer, "POST", f"/api/projects/{pid}/duplicate").json()["id"]
        self.assertEqual(self.req(self.viewer, "GET", f"/api/projects/{copy}").json()["role"], "owner")
        self.req(self.owner, "GET", f"/api/projects/{copy}", status=404)
        self.req(self.owner, "PATCH", f"/api/projects/{pid}", json={"folder": "Campaign", "title": "Renamed", "starred": True})
        item = next(p for p in self.req(self.owner, "GET", "/api/projects").json() if p["id"] == pid)
        self.assertEqual((item["folder"], item["title"], item["starred"]), ("Campaign", "Renamed", True))

    def test_18_comments_and_permissions(self):
        pid = self.project()
        self.member(pid, 2, "view")
        cid = self.req(self.viewer, "POST", f"/api/projects/{pid}/comments", json={"body": "Useful feedback <script>"}).json()["id"]
        self.req(self.viewer, "PUT", f"/api/projects/{pid}/comments/{cid}", status=404, json={"resolved": True})
        self.req(self.owner, "PUT", f"/api/projects/{pid}/comments/{cid}", json={"resolved": True})
        self.assertTrue(self.req(self.owner, "GET", f"/api/projects/{pid}/comments").json()[0]["resolved"])
        for body in ["", "x"*4001]:
            self.req(self.owner, "POST", f"/api/projects/{pid}/comments", status=400, json={"body": body})

    def test_19_presence(self):
        pid = self.project()
        self.member(pid, 1, "edit")
        self.req(self.editor, "POST", f"/api/projects/{pid}/presence")
        v = self.req(self.owner, "POST", f"/api/projects/{pid}/presence").json()
        self.assertEqual(sorted(v["people"]), ["Editor", "Owner"])
        self.req(self.outsider, "POST", f"/api/projects/{pid}/presence", status=404)

    def test_20_malformed_native_document_and_dimensions(self):
        pid = self.project()
        self.upload(pid, b"PK\x03\x04not-a-document", commit_status=400)
        uid = self.begin(pid, width=999)
        self.req(self.owner, "PUT", f"/api/uploads/{uid}/0", data=self.fixture)
        self.req(self.owner, "POST", f"/api/uploads/{uid}/commit", status=400, json={})

    def test_21_metadata_and_session_headers(self):
        r = self.req(self.owner, "GET", "/api/me")
        self.assertEqual(r.headers["Cache-Control"], "no-store")
        self.assertEqual(r.headers["X-Content-Type-Options"], "nosniff")
        self.assertEqual(r.headers["Referrer-Policy"], "no-referrer")

    def test_22_invalid_share_and_auth_callback(self):
        for key in ["short", "0"*64]:
            self.req(self.anon, "GET", f"/api/share/{key}", status=404)
        self.req(self.anon, "GET", "/auth/callback?state=bad&token_hash=bad&type=email", status=400)

    def test_99_logout_revokes_session(self):
        self.req(self.outsider, "POST", "/api/logout", json={})
        self.req(self.outsider, "GET", "/api/me", status=401)

    def test_23_cancel_upload_is_author_scoped(self):
        pid = self.project()
        uid = self.begin(pid)
        self.req(self.outsider, "DELETE", f"/api/uploads/{uid}", status=404)
        self.req(self.owner, "DELETE", f"/api/uploads/{uid}")
        self.req(self.owner, "PUT", f"/api/uploads/{uid}/0", status=404, data=self.fixture)

    def test_24_upload_resource_limits(self):
        pid = self.project()
        base = {"base_revision": 0, "bytes": len(self.fixture), "parts": 1,
                "sha256": hashlib.sha256(self.fixture).hexdigest(), "title": "Bounds", "width": 64, "height": 48}
        for change in [{"bytes": 0}, {"bytes": 104857601}, {"parts": 0}, {"parts": 2},
                       {"width": 0}, {"width": 16385}, {"width": 9000, "height": 9000}, {"sha256": "g"*64}]:
            with self.subTest(change=change):
                self.req(self.owner, "POST", f"/api/projects/{pid}/uploads", status=400, json={**base, **change})
        for _ in range(5):
            self.begin(pid)
        self.req(self.owner, "POST", f"/api/projects/{pid}/uploads", status=400, json=base)

    def test_25_expired_sessions_and_uploads(self):
        pid = self.project()
        uid = self.begin(pid)
        self.db.execute("UPDATE photocraft.uploads SET created_at=now()-interval '2 days' WHERE id=%s", (uid,))
        # A new upload runs bounded expiry cleanup, so stale bytes cannot accumulate forever.
        self.begin(pid)
        self.req(self.owner, "PUT", f"/api/uploads/{uid}/0", status=404, data=self.fixture)
        session = requests.Session()
        session.trust_env = False
        session.headers['Origin'] = BASE
        token = secrets.token_hex(32)
        session.cookies.set('pc_session', token)
        self.db.execute("INSERT INTO photocraft.sessions(hash,account_id,expires_at) VALUES(%s,%s,now()-interval '1 minute')",
                        (hashlib.sha256(token.encode()).hexdigest(), self.accounts[0][0]))
        self.req(session, "GET", "/api/me", status=401)

    def test_26_preview_size_and_access(self):
        from PIL import Image
        pid = self.project()
        f = io.BytesIO()
        Image.new('RGB', (320, 240), '#805bdf').save(f, format='PNG')
        self.req(self.owner, 'PUT', f'/api/projects/{pid}/thumbnail', data=f.getvalue())
        self.assertEqual(self.req(self.owner, 'GET', f'/api/projects/{pid}/thumbnail').content, f.getvalue())
        self.member(pid, 2, 'view')
        self.req(self.viewer, 'PUT', f'/api/projects/{pid}/thumbnail', status=404, data=f.getvalue())
        for data in [b'bad', f.getvalue()[:20], f.getvalue()[:16] + (100000).to_bytes(4, 'big') + f.getvalue()[20:]]:
            self.req(self.owner, 'PUT', f'/api/projects/{pid}/thumbnail', status=400, data=data)

    def test_27_member_validation_and_owner_protection(self):
        pid = self.project()
        for email, role in [('bad', 'edit'), (self.accounts[1][1], 'admin')]:
            self.req(self.owner, 'PUT', f'/api/projects/{pid}/members', status=400, json={'email': email, 'role': role})
        self.req(self.owner, 'PUT', f'/api/projects/{pid}/members', json={'email': self.accounts[0][1], 'role': 'view'})
        self.assertEqual(self.req(self.owner, 'GET', f'/api/projects/{pid}').json()['role'], 'owner')

    def test_28_large_request_rejected(self):
        pid = self.project()
        uid = self.begin(pid)
        self.req(self.owner, 'PUT', f'/api/uploads/{uid}/0', status=413, data=b'x'*(CHUNK+1025))

    def test_29_static_cache_and_download_headers(self):
        import re
        index = self.req(self.anon, 'GET', '/')
        self.assertEqual(index.headers['Cache-Control'], 'no-cache')
        wasm = re.search(r'photocraft-web-[a-z0-9]+_bg\.wasm', index.text)
        self.assertIsNotNone(wasm)
        response = self.req(self.anon, 'HEAD', '/'+wasm.group())
        self.assertIn('immutable', response.headers['Cache-Control'])
        self.assertEqual(response.headers['Content-Type'], 'application/wasm')


if __name__ == "__main__":
    unittest.main(verbosity=2)
